"""baseline schema from models

Revision ID: a73747e2b475
Revises: 
Create Date: 2026-04-21 11:29:17.241035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a73747e2b475'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('custom_api_key_enc', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('raw_name', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('valid_count', sa.Integer(), nullable=True),
    sa.Column('skipped_count', sa.Integer(), nullable=True),
    sa.Column('batch_dir', sa.String(length=255), nullable=False),
    sa.Column('template_strategy', sa.String(length=20), nullable=True),
    sa.Column('fixed_theme_id', sa.String(length=40), nullable=True),
    sa.Column('product_category', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batches_batch_id'), ['batch_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_batches_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_batches_raw_name'), ['raw_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_batches_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_batches_user_id'), ['user_id'], unique=False)

    op.create_table('generation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('api_key_source', sa.String(length=20), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generation_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_logs_user_id'), ['user_id'], unique=False)

    op.create_table('batch_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_pk', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('main_image_path', sa.String(length=500), nullable=True),
    sa.Column('detail_image_paths', sa.Text(), nullable=True),
    sa.Column('desc_text', sa.Text(), nullable=True),
    sa.Column('desc_chars', sa.Integer(), nullable=True),
    sa.Column('skip_reason', sa.String(length=200), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('want_ai_refine', sa.Boolean(), nullable=True),
    sa.Column('ai_refine_status', sa.String(length=20), nullable=True),
    sa.Column('resolved_theme_id', sa.String(length=40), nullable=True),
    sa.Column('resolved_theme_matched_by', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_pk'], ['batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batch_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batch_items_batch_pk'), ['batch_pk'], unique=False)
        batch_op.create_index(batch_op.f('ix_batch_items_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batch_items_status'))
        batch_op.drop_index(batch_op.f('ix_batch_items_batch_pk'))

    op.drop_table('batch_items')
    with op.batch_alter_table('generation_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generation_logs_user_id'))

    op.drop_table('generation_logs')
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batches_user_id'))
        batch_op.drop_index(batch_op.f('ix_batches_status'))
        batch_op.drop_index(batch_op.f('ix_batches_raw_name'))
        batch_op.drop_index(batch_op.f('ix_batches_created_at'))
        batch_op.drop_index(batch_op.f('ix_batches_batch_id'))

    op.drop_table('batches')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    # ### end Alembic commands ###
