// Verify that the 2026-05-27 planning handoff references real local files.

const fs = require("fs");

const requiredPaths = [
  "templates/batch/upload.html",
  "tests/test_batch_upload_ux.py",
  "tests/test_batch_progress_ui.py",
  "tests/test_batch_pipeline_smoke.py",
  "scripts/verify_batch_upload_ux_static.py",
  "scripts/verify_batch_upload_inline_js_syntax.js",
  "scripts/verify_batch_upload_runtime_smoke.js",
  "scripts/verify_batch_upload_ux_all.js",
  "scripts/check_local_dev_env.ps1",
  "scripts/bootstrap_local_dev_env.ps1",
  "scripts/make_upload_ux_sample.ps1",
  "scripts/verify_2026_05_27_commit_manifest.js",
  "scripts/verify_2026_05_27_handoff_all.ps1",
  "scripts/verify_2026_05_27_planning_paths.js",
  "docs/2026-05-27_commit-manifest.md",
  "docs/2026-05-27_handoff-index.md",
  "docs/2026-05-27_next-action-tracker.md",
  "docs/2026-05-27_next-planning-baseline.md",
  "docs/2026-05-27_decision-brief.md",
  "docs/2026-05-27_upload-ux-quick-win-plan.md",
  "docs/2026-05-27_upload-ux-browser-validation-report.md",
  "docs/2026-05-27_upload-ux-browser-validation-runbook.md",
  "docs/2026-05-27_python-flask-env-recovery-options.md",
  "docs/2026-05-27_phase7-readiness-checklist.md",
  "docs/superpowers/audits/2026-05-27-p5-6-consumable-e2e.md",
];

const requiredDocChecks = [
  [
    "docs/2026-05-27_handoff-index.md",
    [
      "docs/2026-05-27_decision-brief.md",
      "docs/2026-05-27_commit-manifest.md",
      "docs/2026-05-27_next-action-tracker.md",
      "docs/2026-05-27_next-planning-baseline.md",
      "docs/2026-05-27_upload-ux-browser-validation-runbook.md",
      "docs/2026-05-27_upload-ux-browser-validation-report.md",
      "docs/2026-05-27_python-flask-env-recovery-options.md",
      "node scripts/verify_2026_05_27_planning_paths.js",
      "scripts/check_local_dev_env.ps1",
      "scripts/bootstrap_local_dev_env.ps1",
      "scripts/make_upload_ux_sample.ps1",
      "scripts/verify_2026_05_27_commit_manifest.js",
      "scripts/verify_2026_05_27_handoff_all.ps1",
      "bootstrap local dev env plan-only OK",
      "sensitive content scan OK: current status files",
      "2026-05-27 planning path checks passed (25 paths)",
      "commit manifest covers git status (23 paths); command draft matches manifest (23 paths)",
      "worktree summary: 1 modified, 22 untracked, 23 total",
      "recommended route:",
      "1 first: commit current worktree to freeze handoff and validation assets",
      "2 next: restore Python/Flask environment and browser-test /batch/upload",
      "next decision options:",
      "entry docs:",
      "commit: docs/2026-05-27_commit-manifest.md",
      "environment: docs/2026-05-27_python-flask-env-recovery-options.md",
      "actions: docs/2026-05-27_next-action-tracker.md",
      "当前卡点",
      "Codex bundled Python",
      "不能替代项目 Flask/pytest 环境",
      "它对应 **2. 先恢复 Python/Flask 环境**",
      "Agent team 只读审查已复核三项拍板入口",
      "当前最稳路线是先选 1 固化当前工作区，再选 2 闭环上传 UX",
      "手测前需用本地测试账号登录",
      "不使用生产账号或生产密码",
      "用本地测试账号登录并做真实浏览器 `/batch/upload` 手测",
      "如果现在只拍一个板",
      "1. 先提交当前工作区",
      "命令草案在提交清单中，只有用户明确选择 1 后执行",
      "2. 先恢复 Python/Flask 环境",
      "3. 暂不动代码，只继续规划",
      "“选 2 时的最小执行顺序”",
      "scripts/bootstrap_local_dev_env.ps1 -ConfirmInstall",
      "test_batch_input/upload_ux_sample",
      "2 个产品目录、6 个产品文件",
      "main.png",
      "detail-1.png",
      "info.txt",
      "synthetic sample / no real customer data",
      "test_batch_input/` 被 git 忽略",
    ],
  ],
  [
    "docs/2026-05-27_next-planning-baseline.md",
    [
      "Agent Team 独立审查",
      "docs/2026-05-27_handoff-index.md",
      "docs/2026-05-27_commit-manifest.md",
      "docs/2026-05-27_next-action-tracker.md",
      "scripts/verify_batch_upload_ux_all.js",
      "scripts/check_local_dev_env.ps1",
      "scripts/bootstrap_local_dev_env.ps1",
      "scripts/make_upload_ux_sample.ps1",
      "scripts/verify_2026_05_27_commit_manifest.js",
      "scripts/verify_2026_05_27_handoff_all.ps1",
      "docs/2026-05-27_upload-ux-browser-validation-runbook.md",
      "docs/2026-05-27_upload-ux-browser-validation-report.md",
      "docs/2026-05-27_python-flask-env-recovery-options.md",
      "Codex bundled Python",
      "common Python candidates: MISSING",
      "docker: MISSING",
      "bootstrap local dev env plan-only OK",
      "sensitive content scan OK: current status files",
      "Codex bundled Python dependency probe",
      "flask",
      "flask: MISSING",
      "playwright",
      "playwright: MISSING",
      "using Python static verifier",
      "stdlib source guard tests passed",
      "test_batch_input is ignored by git",
      "upload UX sample path exists: test_batch_input\\upload_ux_sample",
      "upload UX sample content OK: 2 product dirs, 6 product files",
      "upload UX sample product dirs OK: sample-product-a, sample-product-b",
      "upload UX sample product files OK: main.png, detail-1.png, info.txt",
      "upload UX sample product files are non-empty",
      "upload UX sample PNG headers OK: main.png, detail-1.png",
      "upload UX sample info markers OK: synthetic sample, no real customer data",
      "最新 agent team 只读审查已复核三项拍板入口",
      "审查后已补清“B 上传 UX 快赢验证”对应三项拍板里的“2. 先恢复 Python/Flask 环境”",
      "当前最稳路线是先选 1 固化当前工作区，再选 2 闭环上传 UX",
      "当前也守护 agent team 最新审查结论",
      "当前工作区建议提交清单，含选 1 命令草案",
      "提交清单已包含选 1 命令草案",
      "仅在用户明确选择 1 后执行",
      "不得包含 `test_batch_input/`",
      "用本地测试账号登录后打开 `/batch/upload`",
      "用本地测试账号登录并打开 `/batch/upload`",
      "不使用生产账号或生产密码",
      "worktree summary: 1 modified, 22 untracked, 23 total",
      "handoff verification passed",
      "recommended route:",
      "1 first: commit current worktree to freeze handoff and validation assets",
      "2 next: restore Python/Flask environment and browser-test /batch/upload",
      "next decision options:",
      "1. commit current worktree",
      "2. restore Python/Flask environment",
      "3. planning only; no code/install/network/API",
      "entry docs:",
      "commit: docs/2026-05-27_commit-manifest.md",
      "environment: docs/2026-05-27_python-flask-env-recovery-options.md",
      "actions: docs/2026-05-27_next-action-tracker.md",
      "P5.6",
      "阶段七",
    ],
  ],
  [
    "docs/2026-05-27_decision-brief.md",
    [
      "上传 UX",
      "真实 Flask/浏览器",
      "agent team 只读审查已复核三项拍板入口",
      "仅建议补清“B 对应选 2”的口径",
      "它对应 **2. 先恢复 Python/Flask 环境**",
      "如果想先固化当前工作区，再先选 1，之后再选 2",
      "用本地测试账号登录后打开 `/batch/upload`",
      "如果现在只拍一个板",
      "1. 先提交当前工作区",
      "2. 先恢复 Python/Flask 环境",
      "3. 暂不动代码，只继续规划",
      "“选 2 时的最小执行顺序”",
      "scripts/bootstrap_local_dev_env.ps1 -ConfirmInstall",
      "Codex 捆绑 Python",
      "10 个源码守护测",
      "常见本机 Python 安装目录",
      "Docker 路线当前不能直接执行",
      "sensitive content scan OK: current status files",
      "worktree summary: 1 modified, 22 untracked, 23 total",
      "handoff verification passed",
      "recommended route:",
      "1 first: commit current worktree to freeze handoff and validation assets",
      "2 next: restore Python/Flask environment and browser-test /batch/upload",
      "next decision options:",
      "1. commit current worktree",
      "2. restore Python/Flask environment",
      "3. planning only; no code/install/network/API",
      "entry docs:",
      "commit: docs/2026-05-27_commit-manifest.md",
      "environment: docs/2026-05-27_python-flask-env-recovery-options.md",
      "actions: docs/2026-05-27_next-action-tracker.md",
      "flask",
      "playwright",
      "test_batch_input is ignored by git",
      "upload UX sample path exists: test_batch_input\\upload_ux_sample",
      "upload UX sample content OK: 2 product dirs, 6 product files",
      "upload UX sample product dirs OK: sample-product-a, sample-product-b",
      "upload UX sample product files OK: main.png, detail-1.png, info.txt",
      "upload UX sample product files are non-empty",
      "upload UX sample PNG headers OK: main.png, detail-1.png",
      "upload UX sample info markers OK: synthetic sample, no real customer data",
      "docs/2026-05-27_commit-manifest.md",
      "docs/2026-05-27_upload-ux-browser-validation-runbook.md",
      "docs/2026-05-27_upload-ux-browser-validation-report.md",
    ],
  ],
  [
    "docs/2026-05-27_upload-ux-browser-validation-report.md",
    [
      "当前状态：待执行",
      "登录态/测试账号",
      "需本地账号可登录且 `is_approved=True`",
      "不使用生产账号或生产密码",
      "test_batch_input/upload_ux_sample",
      "bootstrap local dev env plan-only OK",
      "sensitive content scan OK: current status files",
      "using Python static verifier",
      "stdlib source guard tests passed: 10 tests across 2 files",
      "upload UX sample path exists: test_batch_input\\upload_ux_sample",
      "upload UX sample content OK: 2 product dirs, 6 product files",
      "upload UX sample product dirs OK: sample-product-a, sample-product-b",
      "upload UX sample product files OK: main.png, detail-1.png, info.txt",
      "upload UX sample product files are non-empty",
      "upload UX sample PNG headers OK: main.png, detail-1.png",
      "upload UX sample info markers OK: synthetic sample, no real customer data",
      "是否使用真实 API",
      "手动验收结果",
    ],
  ],
  [
    "docs/2026-05-27_upload-ux-quick-win-plan.md",
    [
      "docs/2026-05-27_upload-ux-browser-validation-runbook.md",
      "使用本地测试账号登录",
      "不使用生产账号或生产密码",
      "登录本地测试账号后打开 `/batch/upload`",
      "node scripts/verify_batch_upload_ux_all.js",
      "fetch('/api/batch/upload'",
    ],
  ],
  [
      "docs/2026-05-27_commit-manifest.md",
      [
      "chore: add upload ux handoff and validation baseline",
      "templates/batch/upload.html",
      "commit manifest covers git status (23 paths); command draft matches manifest (23 paths)",
      "2026-05-27 planning path checks passed (25 paths)",
      "tests/test_batch_progress_ui.py",
      "tests/test_batch_pipeline_smoke.py",
      "scripts/make_upload_ux_sample.ps1",
      "scripts/verify_2026_05_27_commit_manifest.js",
      "scripts/verify_2026_05_27_handoff_all.ps1",
      "PowerShell 语法检查",
      "git diff --check",
      "敏感/本地素材路径护栏",
      "git status --short",
      "next decision options:",
      "worktree summary: 1 modified, 22 untracked, 23 total",
      "recommended route:",
      "选 1 时的最小执行顺序",
      "不要 stage `test_batch_input/`",
      "提交后下一步建议接 `2. restore Python/Flask environment`",
      "按 `docs/2026-05-27_python-flask-env-recovery-options.md` 的“选 2 时的最小执行顺序”恢复环境",
      "entry docs:",
      "commit: docs/2026-05-27_commit-manifest.md",
      "environment: docs/2026-05-27_python-flask-env-recovery-options.md",
      "actions: docs/2026-05-27_next-action-tracker.md",
      "使用本地测试账号登录后打开 `/batch/upload`",
      "不使用生产账号或生产密码",
    ],
  ],
  [
    "docs/2026-05-27_next-action-tracker.md",
    [
      "恢复 Python/Flask 本地环境",
      "sensitive content scan OK: current status files",
      "命令草案比对",
      "commit manifest covers git status (23 paths); command draft matches manifest (23 paths)",
      "Codex 捆绑 Python 仅够静态检查",
      "常见本机 Python 安装目录",
      "Docker/Compose",
      "生成上传 UX 本地手测素材",
      "2 个产品目录、6 个产品文件",
      "main.png",
      "detail-1.png",
      "synthetic sample / no real customer data",
      "闭环上传 UX 真实浏览器验证",
      "需本地测试账号可登录且 `is_approved=True`",
      "不使用生产账号或生产密码",
      "用本地测试账号登录",
      "Agent team 最新只读审查结论",
      "当前最稳路线是先选 1 固化当前工作区，再选 2 闭环上传 UX",
      "提交后自然接选 2",
      "## 拍板问题",
      "当前先走哪条线",
      "先提交当前工作区",
      "先恢复 Python/Flask 环境",
      "暂不动代码，只继续规划",
      "scripts/bootstrap_local_dev_env.ps1 -ConfirmInstall",
      "“选 2 时的最小执行顺序”",
      "先确认 Python 路径或授权，再跑只读探针 / `.venv` bootstrap / pytest / 本地 Flask / 浏览器手测",
      "worktree summary: 1 modified, 22 untracked, 23 total",
      "handoff verification passed",
      "recommended route:",
      "1 first: commit current worktree to freeze handoff and validation assets",
      "2 next: restore Python/Flask environment and browser-test /batch/upload",
      "next decision options:",
      "1. commit current worktree",
      "2. restore Python/Flask environment",
      "3. planning only; no code/install/network/API",
      "entry docs:",
      "commit: docs/2026-05-27_commit-manifest.md",
      "environment: docs/2026-05-27_python-flask-env-recovery-options.md",
      "actions: docs/2026-05-27_next-action-tracker.md",
      "需要授权",
      "不能替代项目 Flask/pytest 环境",
      "docs/2026-05-27_commit-manifest.md",
    ],
  ],
  [
    "docs/2026-05-27_upload-ux-browser-validation-runbook.md",
    [
      "/batch/upload",
      "已有本地可登录账号",
      "`is_approved=True`",
      "未登录时会跳转到登录页",
      "flask --app app create-admin",
      "不要为了手测改用生产账号",
      "不触发真实 AI 生成",
      "scripts/make_upload_ux_sample.ps1",
      "scripts/check_local_dev_env.ps1",
      "scripts/bootstrap_local_dev_env.ps1",
      "docs/2026-05-27_python-flask-env-recovery-options.md",
      "main.png",
      "detail-1.png",
      "synthetic sample / no real customer data",
      "-LargeMB",
      "不改变这 6 个标准产品文件的校验口径",
      "上传失败 <status>: <error>",
    ],
  ],
  [
    "docs/2026-05-27_python-flask-env-recovery-options.md",
    [
      "`python` / `py` / `pip`",
      "Codex Desktop 捆绑 Python",
      "常见本机 Python 安装目录",
      "Docker 路线当前不能直接执行",
      "`flask` / `pytest` / `playwright` 均为 MISSING",
      "使用本地测试账号登录",
      "不使用生产账号或生产密码",
      "用本地测试账号登录后做 `/batch/upload` 浏览器手测",
      "选 2 时的最小执行顺序",
      "用户先提供现成 Python 路径，或明确授权创建 `.venv` 并安装依赖",
      "如果有现成 Python，先只读验证该解释器是否可用",
      "如果没有现成 Python，且用户明确授权创建 `.venv`",
      "环境恢复后，先跑项目侧 pytest，再启动本地 Flask",
      "需要授权安装依赖",
      "scripts/check_local_dev_env.ps1",
      "scripts/bootstrap_local_dev_env.ps1",
      "scripts/bootstrap_local_dev_env.ps1 -ConfirmInstall",
      "docs/2026-05-27_upload-ux-browser-validation-runbook.md",
    ],
  ],
];

const forbiddenDocChecks = [
  [
    "docs/2026-05-27_upload-ux-browser-validation-runbook.md",
    [
      "main.jpg",
      "detail-1.jpg",
    ],
  ],
];

const missing = requiredPaths.filter((path) => !fs.existsSync(path));
if (missing.length) {
  console.error("missing planning paths:");
  for (const path of missing) console.error(`- ${path}`);
  process.exit(1);
}

for (const [path, snippets] of requiredDocChecks) {
  const content = fs.readFileSync(path, "utf8");
  const absent = snippets.filter((snippet) => !content.includes(snippet));
  if (absent.length) {
    console.error(`missing snippets in ${path}:`);
    for (const snippet of absent) console.error(`- ${snippet}`);
    process.exit(1);
  }
}

for (const [path, snippets] of forbiddenDocChecks) {
  const content = fs.readFileSync(path, "utf8");
  const present = snippets.filter((snippet) => content.includes(snippet));
  if (present.length) {
    console.error(`forbidden snippets in ${path}:`);
    for (const snippet of present) console.error(`- ${snippet}`);
    process.exit(1);
  }
}

console.log(`2026-05-27 planning path checks passed (${requiredPaths.length} paths)`);
